AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ExternalId:
    Type: String
    Default: external-id
  RoleName:
    Type: String
    Default: "env0-cost-role"
Resources:
  # CostAssumeRole:
  #   UpdateReplacePolicy: "Retain"
  #   Type: "AWS::IAM::Role"
  #   DeletionPolicy: "Retain"
  #   Properties:
  #     Path: "/"
  #     ManagedPolicyArns:
  #     - Ref: "CostPolicy"
  #     MaxSessionDuration: 3600
  #     RoleName: "${RoleName}"
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #       - Condition:
  #           StringEquals:
  #             sts:ExternalId: "${ExternalId}"
  #         Action: "sts:AssumeRole"
  #         Effect: "Allow"
  #         Principal:
  #           AWS: "arn:aws:iam::913128560467:root"
  CostPolicy:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Retain"
    Properties:
      ManagedPolicyName: 
        !Join
          - ""
          - - !Ref RoleName
            - "-policy"
      Path: "/"
      Description: ""
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: "*"
          Action: "ce:GetCostAndUsage"
          Effect: "Allow"
      Roles:
      - Ref: "RoleName"
Outputs:
  ExternalId:
    Value: !Ref ExternalId
    Description: "ExternalID for Env0"
  AssumeRoleArn:
    Value: !GetAtt CostAssumeRole.Arn