# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "env0-acme-tfstate"
    dynamodb_table = "env0-acme-tfstate-lock"
    key            = "1dae1bba-1bb6-486d-bdca-f94ccfc45d55/non-prod/us-west-2/stage/backend/terraform.tfstate"
    region         = "us-west-2"
    role_arn       = "arn:aws:iam::326535729404:role/env0-acme-assume-role"
  }
}
