# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
// terraform {
//   required_version = "~>1.3.0"
//}
provider "aws" {
  region = "us-west-2"
  # Only these AWS Account IDs may be operated on by this template
  # allowed_account_ids = ["244172364962"]
}
